### ISSUE TITLE
menu design

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#1]
**you have to create a menu design. there are three options theatre owner, customer and exit.

for the theatre owner create one more menu as allocate movies & timings and exit.
for the customer create menu as book tickets and exit.**

refer sample.

+-----------------------+
| Start |
+-----------+-----------+
|
v
+------------+-------------+
| Welcome Menu |
| 1. Customer |
| 2. Theatre Owner |
| 3. Exit |
+------------+-------------+
|
v
+------------+-------------+
| Customer Menu |
| 1. Browse Movies |
| 2. Book Tickets |
| 3. exit |
+------------+-------------+
|
v
+------------+-------------+
| Theatre Owner Menu |
| 1. Allocate Movie & time |
| 2. exit
+------------+-------------+
|
v
+------------+-------------+
| End |
+------------+-------------+

**Comment by Vamsineo22** [comment]
created the menu design and added it to the repository. Reviewer, check it and let me know if any changes are required.

**Comment by neocodeRverse** [comment]
The menu is as per the requirements, few minor changes in the naming conventions. The code is reviewed.
