### ISSUE TITLE
Login Module

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#10]
Create Login module for customer. get the email and password from the customer and check signup tables where the user is exist or not.
if email and pass values are same display succuessfully logged In. or else display wrong email and password.

**Comment by shobana94** [comment]
chandu will help you to get more about signup table. he will explain what all are column available in the table.
Based on that make vaildation in the login module

**Comment by Vamsineo22** [comment]
created the customer login module. Reviewer check it and let me know if any changes are required to be made.

**Comment by neocodeRverse** [comment]
The code is reviewed and required changes are explained clearly.

**Comment by neocodeRverse** [comment]
Waiting for the update on required changes

**Comment by Vamsineo22** [comment]
email and password verification is completed. Required changes are updated

**Comment by neocodeRverse** [comment]
The code is verified and the changes are as per the requirement.!
