### ISSUE TITLE
Theatre Owner Module

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#22]

**Comment by GONTLASRILIKITHA3579** [comment]
[book (2).zip](https://github.com/shobana94/bookMyShow_Clone/files/14953664/book.2.zip)

**Comment by GONTLASRILIKITHA3579** [comment]
I have completed the given task, check the file, and if any updates let me know

**Comment by neocodeRverse** [comment]
The Owner should have one more field seats availability and tickets price, make sure add those and update the methods.

**Comment by GONTLASRILIKITHA3579** [comment]
I have added seat availability and ticket price and updated the methods also
