### ISSUE TITLE
Payment Module

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#23]

**Comment by neo-chandu** [comment]
[payment.zip](https://github.com/shobana94/bookMyShow_Clone/files/14974045/payment.zip)

**Comment by neo-chandu** [comment]
I have completed the given task, check the file, and if any updates let me know

**Comment by neocodeRverse** [comment]
The codes are in standard, make sure to add one more module to get all the payments history

**Comment by neocodeRverse** [comment]
Also in the payment field Mapping is must to movies, map is with movieID, add the changes and let me know.

**Comment by neo-chandu** [comment]
[payment.zip](https://github.com/shobana94/bookMyShow_Clone/files/14974417/payment.zip)

**Comment by neo-chandu** [comment]
> Also in the payment field Mapping is must to movies, map is with movieID, add the changes and let me know.
