### ISSUE TITLE
Draw usecase diagram for our project

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#27]
add all the users and functionalities. use any online tool to draw the diagram.

**Comment by GONTLASRILIKITHA3579** [comment]
I have completed it, let me know if any changes are required!
![BookMy Show Use Case D](https://github.com/shobana94/bookMyShow_Clone/assets/164048911/e4b0f96c-80a9-4525-b301-e62c9d1287e7)

**Comment by shobana94** [comment]
diagram verified
