### ISSUE TITLE
ER Diagram 

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#28]
use any online tool to draw the diagram. add all the users and functionalities for our projects

**Comment by neo-chandu** [comment]
![WhatsApp Image 2024-04-02 at 10 42 54](https://github.com/shobana94/bookMyShow_Clone/assets/163999633/61f10679-a643-4a4c-81f7-da60fc7bd102)

**Comment by neo-chandu** [comment]
ER diagram is done, let me know if any changes are to be made.

**Comment by shobana94** [comment]
Diagram verified
