### ISSUE TITLE
Ticket View

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#4]
Generate the booked tickets
once the customer booked the movie display the movie name, timing and price
get the data from the database.

**Comment by neo-chandu** [comment]
Uploaded to the repository

**Comment by neo-chandu** [comment]
uploaded to the repository

**Comment by neocodeRverse** [comment]
the code has to be changed, for the ticket timings logic, instead of timings its printing the "TIME" for every input.

**Comment by neocodeRverse** [comment]
The code review is completed
