### ISSUE TITLE
Display movie list

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#5]
display the available movie names and let the user to select the movie name

**Comment by shobana94** [comment]
task completed any updates let me know

**Comment by neocodeRverse** [comment]
The timings logic in the code has to be modified, the review is complete, update the logic as per the requirements.

Instead of printing the timings it returning "TIME" for every input, update me once the changes are completed.

**Comment by shobana94** [comment]
changes are updated
