### ISSUE TITLE
Create Theatre owner module

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#8]
you have to create theatre owner module. the owner has to enter the movieName, TicketPrice, TimeSlot, NumberOfSeats and all the values will be inserted into table. 

table Name =  MovieSchedule
column names = Movieid (Auto increment), MovieName, TicketPrice, TimeSlot (TIME format=08:30:00 ), NumberOfSeats)

**Comment by neocodeRverse** [comment]
The columns are modified as the requirement and the changes are made.

**Comment by shobana94** [comment]
You  have to create console based module. Get all the details from console and store it in respective tables

**Comment by shobana94** [comment]
Don't directly add all the values in tables. Using console only u have to insert all the values

**Comment by shobana94** [comment]
raghuveer try to upload you code in respective repository. still your repository is empty.

**Comment by neocodeRverse** [comment]
The code is updated in the branch

**Comment by neocodeRverse** [comment]
Also the code is reviewed
