### ISSUE TITLE
Signup Module

### ISSUE THREAD

**Issue by shobana94** [shobana94/bookMyShow_Clone#9]
You have to create a login module for customer. the customer has to enter the name, phone number, emailid, password and confirmPassword.

and store all the values inside the tables.
Sample column values as Cid, Cname, Cphn, Cmail, Cpass, CconfirmPass.

**Comment by neo-chandu** [comment]
uploaded to repository

**Comment by neocodeRverse** [comment]
The login module code is not uploaded, the code is missing from the repository. Make sure to check again, also add the requirement in the text file.

**Comment by neocodeRverse** [comment]
#Signup module

**Comment by shobana94** [comment]
reghuveer kindly review this module
